SNotes/Models/Label.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SNotes.Models
{
    public class Label
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string UserId { get; set; }
        public virtual IList<Note> Notes { get; set; }
    }
}

SNotes/Controllers/LabelController.cs
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using SNotes.Repositories;
using SNotes.ViewModels;

namespace SNotes.Controllers
{
    public class LabelController : Controller
    {

        // GET: Label
        public ActionResult Index()
        {
            return View();
        }

        private readonly ILabelRepository _repository;

        public LabelController(ILabelRepository repository)
        {
            _repository = repository;
        }


        // GET: Note


        public ActionResult LabelList()
        {
            var labels = _repository.GetLabelList(User.Identity.GetUserId());

            return View("_labelListPartial", labels);
            
        }

        [HttpGet]
        public ActionResult Create()
        {
            var model = new AddLabelViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(AddLabelViewModel model)
        {
            if (ModelState.IsValid)
            {
                _repository.Save(model);
                return RedirectToAction("NoteList", "Note");
            }

            return View(model);
            
        }

        [HttpGet]
        public ActionResult Edit(long id)
        {
            var model = _repository.Get(id);
            return View(model);
  
        }

        [HttpPost]
        public ActionResult Edit(EditLabelViewModel model)
        {
            if (ModelState.IsValid)
            {
                _repository.Update(model);
                return RedirectToAction("Notelist", "Note");
            }

            return View(model);
            
        }

        [HttpPost]
        public ActionResult Delete(long id)
        {
            _repository.Delete(id);

            return RedirectToAction("NoteList", "Note");
           
        }

    }
}

SNotes/Views/Label/Create.cshtml
@using System.Web.Mvc.Html


<div class="row">
    <div class="col-md-3">

        @{Html.RenderAction("LabelList", "Label"); }

    </div>

    <div class="col-md-8">
        <div style="width: 85%">
            @{
                Html.RenderPartial("_createLabelPartial");
            }
        </div>
    </div>

    <div class="col-md-1">
    </div>
</div>
















































@*@model SNotes.ViewModels.AddLabelViewModel

@{
    ViewBag.Title = "Create";
}

<h2>New Label</h2>
 
    @using(Html.BeginForm("Create", "Label"))
    { 
        <div class="form-group">
            @Html.LabelFor(m => m.Name)
            @Html.TextBoxFor(m => m.Name, new {@class = "form-control"})
        
        </div>
    
        <button type="submit" class="btn btn-default">Submit</button>
    }*@

SNotes/Views/Label/Edit.cshtml
@using System.Web.Mvc.Html


<div class="row">
    <div class="col-md-3">

        @{Html.RenderAction("LabelList", "Label"); }

    </div>

    <div class="col-md-8">
        <div style="width: 85%">
            @{
                Html.RenderPartial("_editLabelPartial");
            }
        </div>
    </div>

    <div class="col-md-1">
    </div>
</div>










































@*@model SNotes.ViewModels.EditLabelViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>New Label</h2>
 
    @using(Html.BeginForm("Edit", "Label"))
    { 
        <div class="form-group">
            @Html.LabelFor(m => m.Name)
            @Html.TextBoxFor(m => m.Name, new {@class = "form-control"})
        
        </div>
    
        <button type="submit" class="btn btn-default">Submit</button>
    }*@